name: jiyi
description: "Cross platform encrypted audio logging app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  pointycastle: ^4.0.0
  flutter_recorder: ^1.1.1
  collection: ^1.19.1
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  file_picker: ^9.2.3
  permission_handler: ^12.0.0+1
  local_auth: ^2.3.0
  path: ^1.9.1
  wav: ^1.4.0
  json_annotation: ^4.9.0
  flutter_map_marker_cluster: any
  flutter_map: any
  flutter_map_cache: any
  http_cache_file_store: any
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  latlong2: ^0.9.1
  archive: ^4.0.7
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_app_name_localization: ^0.0.6
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter_app_name_localization:
  default: "记忆"
  locales:
    - locale: "en"
      name: "jiyi"

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: 851手写杂书体
      fonts:
        - asset: fonts/851手写杂书体.ttf
    - family: 朱雀仿宋
      fonts:
        - asset: fonts/朱雀仿宋.ttf
    - family: digital7-mono
      fonts:
        - asset: fonts/digital-7-mono.ttf
