name: jiyi
description: "Cross platform encrypted audio logging app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.4
  pointycastle: ^4.0.0
  flutter_recorder: ^1.1.1
  collection: ^1.19.1
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  file_picker: ^9.2.3
  permission_handler: ^12.0.0+1
  local_auth: ^2.3.0
  flutter_map: ^8.1.1
  path: ^1.9.1
  wav: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_app_name_localization: ^0.0.6
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: 851手写杂书体
      fonts:
        - asset: fonts/851手写杂书体.ttf
    - family: 朱雀仿宋
      fonts:
        - asset: fonts/朱雀仿宋.ttf
    - family: digital7-mono
      fonts:
        - asset: fonts/digital-7-mono.ttf

flutter_app_name_localization:
  default: "记忆"
  locales:
    - locale: "en"
      name: "jiyi"
