// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Tokenizer tokenizerFromConfig({required String configPath}) =>
    RustLib.instance.api.crateApiTokenizerFromConfig(configPath: configPath);

Int64List encode({required Tokenizer tokenizer, required String input}) =>
    RustLib.instance.api.crateApiEncode(tokenizer: tokenizer, input: input);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Tokenizer>>
abstract class Tokenizer implements RustOpaqueInterface {}
