// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AHashMap < String , u32 >>>
abstract class AHashMapStringU32 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BPE>>
abstract class Bpe implements RustOpaqueInterface {
  static BpeBuilder builder() =>
      RustLib.instance.api.crateApiModelsBpeBpeBuilder();

  void clearCache();

  static BpeBuilder fromFile({required String vocab, required String merges}) =>
      RustLib.instance.api
          .crateApiModelsBpeBpeFromFile(vocab: vocab, merges: merges);

  void getContinuingSubwordPrefix();

  void getUnkToken();

  Map<String, int> getVocab();

  BigInt getVocabSize();

  String? idToToken({required int id});

  factory Bpe(
          {required AHashMapStringU32 vocab,
          required List<(String, String)> merges}) =>
      RustLib.instance.api
          .crateApiModelsBpeBpeNew(vocab: vocab, merges: merges);

  static (AHashMapStringU32, List<(String, String)>) readFile(
          {required String vocab, required String merges}) =>
      RustLib.instance.api
          .crateApiModelsBpeBpeReadFile(vocab: vocab, merges: merges);

  int? tokenToId({required String token});

  List<Token> tokenize({required String sequence});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BpeBuilder>>
abstract class BpeBuilder implements RustOpaqueInterface {
  Bpe build();

  BpeBuilder byteFallback({required bool byteFallback});

  BpeBuilder cacheCapacity({required BigInt capacity});

  BpeBuilder continuingSubwordPrefix({required String prefix});

  BpeBuilder dropout({required double dropout});

  BpeBuilder endOfWordSuffix({required String prefix});

  BpeBuilder files({required String vocab, required String merges});

  BpeBuilder fuseUnk({required bool fuseUnk});

  BpeBuilder ignoreMerges({required bool ignoreMerges});

  factory BpeBuilder() => RustLib.instance.api.crateApiModelsBpeBpeBuilderNew();

  BpeBuilder unkToken({required String unkToken});

  BpeBuilder vocabAndMerges(
      {required AHashMapStringU32 vocab,
      required List<(String, String)> merges});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Token>>
abstract class Token implements RustOpaqueInterface {}
