// To annotate this piece of code is generated by AI
abstract class AI {
  const AI();
}

class DeepSeek extends AI {
  const DeepSeek();
}

class Grok extends AI {
  const Grok();
}

class Qwen extends AI {
  const Qwen();
}

class Copilot extends AI {
  const Copilot();
}

class Claude extends AI {
  const Claude();
}
