// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/bpe.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

int id({required Token t}) => RustLib.instance.api.crateApiTokenizerId(t: t);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Tokenizer>>
abstract class Tokenizer implements RustOpaqueInterface {
  factory Tokenizer({required Bpe model}) =>
      RustLib.instance.api.crateApiTokenizerTokenizerNew(model: model);
}
