name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.config.target }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            asset_name: android-v8a-fdroid-release.apk
            artifact_name: build/app/outputs/apk/fdroid/release/app-fdroid-release.apk
            target: Android
          - os: ubuntu-latest
            asset_name: jiyi-${{ github.ref_name }}-x86_64.AppImage
            artifact_name: jiyi-${{ github.ref_name }}-x86_64.AppImage
            target: Linux

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable

      - name: Build Linux
        if: matrix.config.target == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev \
                                  libpam0g-dev \
                                  libgstreamer1.0-dev \
                                  libgstreamer-plugins-base1.0-dev \
                                  libsecret-1-dev \
                                  libasound2-dev \
                                  squashfs-tools \
                                  libfuse2
          # The official appimage docker image is trash, let's do it manually
          curl https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage \
               -Lo appimage-builder
          chmod +x appimage-builder
          flutter build linux --release
          cp -r build/linux/x64/release/bundle ./AppDir
          ./appimage-builder --skip-tests

      - name: Setup Gradle
        if: matrix.config.target == 'Android'
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Setup android tools (Android)
        if: matrix.config.target == 'Android'
        uses: android-actions/setup-android@v3
        with:
          packages: "ndk;26.1.10909125 ndk;26.3.11579264 ndk;27.0.12077973 build-tools;35.0.0 platforms;android-35 platform-tools"

      - name: Build Android
        if: matrix.config.target == 'Android'
        run: |
          set -ex
          export JIYI=$(pwd)
          cd $HOME
          git clone https://github.com/alnitak/flutter_soloud
          git clone https://github.com/k2-fsa/sherpa-onnx
          export FLUTTER=$(dirname $(which flutter))
          export FLUTTER_SOLOUD=$HOME/flutter_soloud
          export ANDROID_NDK=$ANDROID_HOME/ndk/$(ls $ANDROID_HOME/ndk/ | tail -n1)
          export SHERPA_ONNX=$HOME/sherpa-onnx

          cd $JIYI
          export SOLOUD_VERSION=$(sed -nE 's/.*flutter_soloud:\s*\^?([0-9.]+).*/\1/p' pubspec.yaml)
          export SHERPA_VERSION=$(sed -nE 's/.*sherpa_onnx:\s*\^?([0-9.]+).*/\1/p' pubspec.yaml)
          export RECORDER_VERSION=$(sed -nE 's/.*flutter_recorder:\s*\^?([0-9.]+).*/\1/p' pubspec.yaml)

          flutterVersion=$(sed -nE 's/\s*flutter:\s*"\^([0-9.]+)".*/\1/p' pubspec.yaml)
          git -C $FLUTTER checkout -f $flutterVersion
          flutter config --no-analytics
          flutter pub get

          find $PUB_CACHE -type f -name "*.wasm" -exec rm -f {} \;
          find $PUB_CACHE -type f -name "*.so" -exec rm -f {} \;
          find $PUB_CACHE -type f -name "*.zip" -exec rm -f {} \;
          find $PUB_CACHE -type f -name "*.gz" -exec rm -f {} \;
          rm -rf $PUB_CACHE/hosted/pub.dev/analyzer-*/example/ddd03.exe
          rm -rf $PUB_CACHE/hosted/pub.dev/gsettings-*/test/dconf/test
          rm -rf $PUB_CACHE/hosted/pub.dev/audioplayers-*/example

          pushd $FLUTTER_SOLOUD/android
          gradle build
          cp -r ./libs/* "$PUB_CACHE/hosted/pub.dev/flutter_soloud-$SOLOUD_VERSION/android/libs/"
          popd

          pushd $SHERPA_ONNX
          cp "$ANDROID_NDK/build/cmake/android-legacy.toolchain.cmake" "$ANDROID_NDK/build/cmake/android-legacy.toolchain.cmake.bak"
          sed -i '/list(APPEND ANDROID_COMPILER_FLAGS/{N;N;s/\n[[:space:]]*-g\n/\n/}' "$ANDROID_NDK/build/cmake/android-legacy.toolchain.cmake"
          ./build-android-arm64-v8a.sh
          cp build-android-arm64-v8a/install/lib/lib*.so $PUB_CACHE/hosted/pub.dev/sherpa_onnx_android-$SHERPA_VERSION/android/src/main/jniLibs/arm64-v8a/
          cp -f "$ANDROID_NDK/build/cmake/android-legacy.toolchain.cmake.bak" "$ANDROID_NDK/build/cmake/android-legacy.toolchain.cmake"
          popd

          touch $PUB_CACHE/hosted/pub.dev/flutter_recorder-$RECORDER_VERSION/web/libflutter_recorder_plugin.wasm
          touch $PUB_CACHE/hosted/pub.dev/flutter_soloud-$SOLOUD_VERSION/web/libflutter_soloud_plugin.wasm
          flutter build apk --flavor fdroid

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ matrix.config.artifact_name }}
          asset_name: ${{ matrix.config.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
