name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.config.target }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            files: build/app/outputs/flutter-apk/app-*-release.apk
            target: Android
          - os: ubuntu-latest
            files: jiyi-${{ github.ref_name }}-x86_64.AppImage
            target: Linux
          # - os: windows-latest
          #   files: jiyi-${{ github.ref_name }}-x86_64_windows.zip
          #   target: Windows

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          version: "3.38.7"

      - name: Get dependencies
        run: flutter pub get

      - name: Generate Code
        run: |
          dart run build_runner build --force-jit --build-filter 'package:jiyi/utils/data/*'

      - name: Build Linux
        if: matrix.config.target == 'Linux'
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev \
                                  libpam0g-dev \
                                  libgstreamer1.0-dev \
                                  libgstreamer-plugins-base1.0-dev \
                                  libsecret-1-dev \
                                  libasound2-dev \
                                  squashfs-tools \
                                  libfuse2
          # The official appimage docker image is trash, let's do it manually
          pip install git+https://github.com/AppImageCrafters/appimage-builder.git
          flutter build linux --release
          cp -r build/linux/x64/release/bundle ./AppDir
          appimage-builder

      # - name: Setup Zip
      #   if: matrix.config.target == 'Windows'
      #   uses: MinoruSekine/setup-scoop@v4
      #   with:
      #     apps: zip
      #
      # - name: Build Windows
      #   if: matrix.config.target == 'Windows'
      #   run: |
      #     Set-PSDebug -Trace 1
      #     flutter build windows --release
      #     cp -r build/windows/x64/runner/Release/ jiyi
      #     zip -9 -r jiyi-${{ github.ref_name }}-x86_64_windows.zip jiyi

      - name: Setup Gradle
        if: matrix.config.target == 'Android'
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14"

      - name: Setup Android NDK
        if: matrix.config.target == 'Android'
        uses: android-actions/setup-android@v3
        with:
          packages: "ndk;28.2.13676358"

      - name: Build Android
        if: matrix.config.target == 'Android'
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y pandoc

          flutter config --no-analytics
          flutter pub get
          FLUTTER_RECORDER=$(sed -nE '/"name": "flutter_recorder"/{n;s/.*"rootUri": "file:\/\/(.*)",/\1/p;}' .dart_tool/package_config.json)
          FLUTTER_SOLOUD=$(sed -nE '/"name": "flutter_soloud"/{n;s/.*"rootUri": "file:\/\/(.*)",/\1/p;}' .dart_tool/package_config.json)
          test -d "$FLUTTER_RECORDER" && test -d "$FLUTTER_SOLOUD"
          export ANDROID_NDK="$ANDROID_HOME/ndk/28.2.13676358"
          export ANDROID_NDK_HOME="$ANDROID_NDK"
          test -d "$ANDROID_NDK"
          # sed -i -e 's/ndkVersion .*/ndkVersion = "28.2.13676358"/' {$PUB_CACHE/hosted/pub.dev/{flutter_recorder-*,flutter_soloud-*,sherpa_onnx_android-*}/android}/build.gradle.kts

          find $PUB_CACHE -type f \
            -regex ".*\.\(wasm\|so\|zip\|gz\|exe\)$" \
            ! -path "*/flutter_recorder-*/android/libs/*" \
            ! -path "*/sherpa_onnx_android-*/android/src/main/jniLibs/*" \
            -exec rm -f {} \;
          rm -rf $PUB_CACHE/hosted/pub.dev/gsettings-*/test/dconf/test
          rm -rf $PUB_CACHE/hosted/pub.dev/audioplayers-*/example

          pushd "$FLUTTER_SOLOUD/xiph"
          ./build_Android.sh
          cp -a android ..
          popd

          touch "$FLUTTER_RECORDER/web/libflutter_recorder_plugin.wasm"
          touch "$FLUTTER_SOLOUD/web/libflutter_soloud_plugin.wasm"
          rm -rf "$FLUTTER_SOLOUD"/xiph/build-*

      - name: Build Android APK
        if: matrix.config.target == 'Android'
        run: flutter build apk --split-per-abi --no-pub

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ matrix.config.files }}
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
